version: '2'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1

services:
  kdc:
    networks:
      custom:
        ipv4_address: 172.21.0.2
    image: sequenceiq/kerberos
    hostname: kdc.kerberos.com
    environment:
      REALM: EXAMPLE.COM
      DOMAIN_REALM: EXAMPLE.COM
      TZ: Asia/Bangkok
    ports:
      - 88:88/udp
      - 749:749
    volumes:
      - "./config_files/krb5.conf:/etc/krb5.conf"
      - "/dev/urandom:/dev/random"
        #- "/etc/localtime:/etc/localtime:ro"

  phoenix-secure:
    networks:
      custom:
        ipv4_address: 172.21.0.3
    image: knappek/phoenix-secure
    depends_on: 
      - kdc
    hostname: phoenix
    domainname: docker.com
    tty: true
    extra_hosts:
      - "kdc.kerberos.com kdc:172.21.0.2"
    environment:
      KRB_REALM: EXAMPLE.COM
      DOMAIN_REALM: EXAMPLE.COM
      FQDN: phoenix.docker.com
      TZ: Asia/Bangkok
    ports:
      - 2181:2181
      - 50010:50010
      - 50070:50070
      - 50075:50075
      - 50090:50090
    volumes:
      - "./config_files/krb5.conf:/etc/krb5.conf"
        #- "/var/db/timezone/zoneinfo/Asia/Bangkok:/etc/localtime:ro"
